version: "3"
services:
  web:
    image: lalleball/htg-it-wms-web
    ports:
      - "80:80"
  scala:
    image: lalleball/htg-it-wms:0.1.0
    restart: always
    networks: 
      - backend
    links:
      - "mysql:database"
    depends_on:
      - "mysql"
  nginx_proxy:
    image: lalleball/nginx_reverse_proxy
    ports:
      - "9000:9001"
    networks:
      - backend
    links:
      - "scala:api"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootwachtwoord # niet voor productie
      MYSQL_DATABASE: databasenaam
      MYSQL_USER: gebruikersnaam
      MYSQL_PASSWORD: wachtwoord
    networks:
      - backend
networks:
  backend: